source 'https://rubygems.org'

gem 'rails', '4.1.4'

gem 'activerecord-session_store', github: 'rails/activerecord-session_store'
gem 'acts-as-taggable-on'
gem 'browser'
gem 'coffee-rails', '~> 4.0.0'
gem 'compass-rails'
gem 'counter_culture'
gem 'daemons'
gem 'delayed_job', '4.0.2'
gem 'delayed_job_active_record'
gem 'devise'
gem 'draper'
gem 'enumerize'
gem 'execjs'
gem 'figaro'
gem 'foreigner'
gem 'gon'
gem 'haml-rails'
gem 'jquery-rails'
gem 'kaminari'
gem 'meta-tags', require: 'meta_tags'
gem 'mysql2'
gem 'newrelic_rpm'
gem 'oj'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'paperclip'
gem 'paranoia', '~> 2.0'
gem 'sass-rails', '~> 4.0.0'
gem 'simple_form'
gem 'therubyracer'
gem 'uglifier', '>= 1.3.0'
gem 'unicorn'
gem 'whenever', require: false

group :development do
  gem 'annotate', '>= 2.6.0'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'bullet'
  gem 'capistrano', '~> 3.2.0'
  gem 'capistrano-rails'
  gem 'capistrano-rvm'
  gem 'capistrano-bundler'
  gem 'capistrano3-unicorn'
  gem 'letter_opener'
  gem 'meta_request'
  gem 'pry-remote'
  gem 'quiet_assets'
  gem 'spring'
end

group :development, :test do
  gem 'awesome_print'
  gem 'hirb'
  gem 'hirb-unicode'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'pry-stack_explorer'
  gem 'rspec-rails'
end

group :development, :staging, :test do
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'gimei'
end
