default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:


development:
  <<: *default

  database: ikikau_development
  socket: /tmp/mysql.sock


test:
  <<: *default

  database: ikikau_test
  socket: /tmp/mysql.sock


production:
  <<: *default

  host:     127.0.0.1
  database: ikikau_production
  username: ikikau_p
  password: <%= ENV['DATABASE_PASSWORD'] %>
