default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:


development:
  <<: *default

  database: ikikau_development
  socket: /tmp/mysql.sock


test:
  <<: *default

  database: ikikau_test
  socket: /tmp/mysql.sock


production:
  <<: *default

  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_DATABASE'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
