default: &default

  account_mail:
    from:      行き交う
    address:   noreply@ikikau.com
    user_name: ikikau@gmail.com
    server:    smtp.mandrillapp.com
    password:  <%= ENV['MANDRILL_KEY'] %>

  url:
    protocol: 'http://'
    host:     'localhost:3000'


development:
  <<: *default

  secret_key_base: <%= ENV['RAILS_SECRET_KEY_BASE'] %>


test:
  <<: *default

  secret_key_base: <%= ENV['RAILS_SECRET_KEY_BASE'] %>


production:
  <<: *default

  secret_key_base: <%= ENV['RAILS_SECRET_KEY_BASE'] %>

  url:
    protocol: 'http://'
    host:     'ikikau.com'
