default: &default

  account_mail:
    from:      dely アカウント
    address:   noreply@dely.jp
    user_name: delyjp.develop@gmail.com
    server:    smtp.mandrillapp.com
    password:  <%= ENV['ACCOUNT_MAIL_PASSWORD'] %>

  url:
    protocol: 'http://'
    host:     'localhost:3000'


development:
  <<: *default

  secret_key_base: b8a3c7708651ef73631004d8d9c02d4d406c24afbeb1ee3797cd1fdd419671006bfc66563b4aa76c69e56a769d26d6d565955cfc1d21d61d0b3d2443b293add6


test:
  <<: *default

  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>


production:
  <<: *default

  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

  url:
    protocol: 'http://'
    host:     'ikikau.com'

